#!/usr/bin/env python3
"""Rebuild docs/lab2/index.html from the template + embedded datasets.
Datasets are regenerated by build-datasets.py (needs the Kimatch repo dumps
and E-GERET output/ files); coast.json comes from Natural Earth 110m coastline."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(HERE, '..', '..', 'docs', 'lab2')
t = open(os.path.join(HERE, 'index.template.html'), encoding='utf-8').read()
for ph, fn in [('__GAZ__', 'gazetteer.json'), ('__LEX__', 'lexicon.json'),
               ('__QUEUE__', 'queue.json'), ('__MAP__', 'mapdata.json'), ('__COAST__', 'coast.json')]:
    blob = open(os.path.join(HERE, 'data', fn), encoding='utf-8').read()
    assert '</script' not in blob.lower(), fn
    t = t.replace(ph, blob)
open(os.path.join(DOCS, 'index.html'), 'w', encoding='utf-8').write(t)
print('docs/lab2/index.html rebuilt')
